<?php /* @var $this Netresearch_Billsafe_Block_Adminhtml_Sales_Order_View_Payment_Overview */ ?>
<?php if ($this->getDirectPaymentCollection()->getSize()): ?>
<div id="billsafe_direct_payments">
    <table style="width: 100%; border-top: 1px solid black; margin-top: 20px;">
        <thead>
            <tr>
                <th><?php echo $this->__("Date") ?></th>
                <th><?php echo $this->__("Amount") ?></th>
                <th><?php echo $this->__("Before") ?></th>
                <th><?php echo $this->__("After") ?></th>
            </tr>
        </thead>
        <tbody>
            <?php /* @var $_directPayment Netresearch_Billsafe_Model_Direct_Payment */ ?>
            <?php foreach ($this->getDirectPaymentCollection() as $_directPayment): ?>
                <tr>
                    <td><?php echo $_directPayment->getCreatedAtFormatted() ?></td>
                    <td><?php echo $this->formatAmount($_directPayment->getBaseReportAmount()) ?></td>
                    <td><?php echo $this->formatAmount($_directPayment->getBaseTotalBefore()) ?></td>
                    <td><?php echo $this->formatAmount($_directPayment->getBaseTotalAfter()) ?></td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>
<?php endif; ?>